# Generated by Django 3.0.6 on 2020-07-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branche',
            new_name='branches',
        ),
    ]
