# Generated by Django 3.0.6 on 2020-07-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20200703_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='bank_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
            preserve_default=False,
        ),
    ]
